---
- name: sort out builtin and custom users and passwords
  hosts: all:!offline
  gather_facts: false
  become: true

  pre_tasks:
    - name: load vault
      include_vars:
        file: ~/.ansible/.picocluster.yml
      run_once: true
#      no_log: true
      tags: ['always']

  tasks:
  - name: Disable ssh root login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes

  - name: restart ssh
    service:
      name: sshd
      state: restarted

  - name: Add a new user named pico
    user:
      name: pico
      shell: /bin/bash
      password: "{{ pico_hashed_pass }}"

  - name: Add pico user to the sudoers
    copy:
      dest: "/etc/sudoers.d/pico"
      content: "pico  ALL=(ALL)  NOPASSWD: ALL"
      validate: /usr/sbin/visudo -cf %s

  - name: Deploy SSH Key
    authorized_key:
      user: pico
      key: "{{ lookup('file', 'pico_id_ecdsa.pub') }}"
      state: present
    tags: sshkey

  - name: update builltin password
    user:
      name: "{{ builtin_user }}"
      password: "{{ builtin_hashed_password }}"

  # - name: Disable Password Authentication
  #   lineinfile:
  #     dest: /etc/ssh/sshd_config
  #     regexp: '^PasswordAuthentication'
  #     line: "PasswordAuthentication no"
  #     state: present
  #     backup: yes
  #   notify:
  #     - restart ssh

# these are utility tasks
  - name: restart ssh only
    service:
      name: sshd
      state: restarted
    tags: ['never','restartssh']

  - name: "unlock {{ builtin_user }}"
    user:
      name: "{{ builtin_user }}"
    tags: ['never','unlock']
