---
- name: use --tags=shutdown or --tags=reboot
  hosts: all:!offline
  gather_facts: false
  become: true

  pre_tasks:
    - name: load vault
      include_vars:
        file: ~/.ansible/.picocluster.yml
      run_once: true
      no_log: true
      tags: ['always']

  tasks:
    - name: "{{ ansible_user }}"
      debug:
        msg: "{{ ansible_user }}"
      tags: ['never', 'debug']

    - name: shutdown
      community.general.shutdown:
      tags: ['never', 'shutdown']

    - name: reboot, wait 5 (total of 10)
      reboot:
        reboot_timeout: 300
      tags: ['never', 'reboot']