---
- name: mount gluster volumes
  hosts: picocluster:!offline
  gather_facts: False
  become: True

  vars:
    enable_cgroup_memory: 'cgroup_enable=memory cgroup_memory=1 '

  pre_tasks:
    - name: load vault
      include_vars:
        file: ~/.ansible/.picocluster.yml
      run_once: True
      tags: ['always']

  tasks:
    - name: Use replace to insert phrase only if it is not there.
      ansible.builtin.replace:
        path: /boot/firmware/cmdline.txt
        backup: False
        regexp: '^(?!{{enable_cgroup_memory}})'
        replace: '{{enable_cgroup_memory}}'
    
    - name: reboot
      reboot:

    - name: snap install microk8s
      community.general.snap:
        name: microk8s
        classic: True

- name: 