---
# tasks file for useiptables
#

- name: Stop, disable, mask firewalld
  ansible.builtin.systemd:
    name: 'firewalld'
    state: stopped
    enabled: no
    masked: yes

- name: install iptables
  ansible.builtin.package:
    name: 'iptables-services'
    state: present


- name: Unmask, enable, start iptables
  ansible.builtin.systemd:
    name: 'iptables'
    state: started
    enabled: yes
    masked: no

#- name: Switch to the legacy variant of iptables because of a bug in the nft version
#  alternatives:
#    name: iptables
#    path: /usr/sbin/iptables-legacy
#    link: /etc/alternatives/iptables
#  notify: Reboot
