---
- name: install, configure, and implement gluster
  hosts: picocluster:!offline
  gather_facts: false
  become: true

  pre_tasks:
    - name: load vault
      include_vars:
        file: ~/.ansible/.picocluster.yml
      run_once: true
      tags: ['always']

  tasks:
# modprobe fuse
    - name: modprobe fuse
      community.general.modprobe:
        name: fuse
        state: present
      tags: ['fuse']

# apt-get install -y xfsprogs glusterfs-server
    - name: install prerequisites
      ansible.builtin.apt:
        pkg:
          - xfsprogs 
          - glusterfs-server
      tags: ['prereqs']

# systemctl start glusterd
    - name: start gluster daemon
      ansible.builtin.systemd:
        name: glusterd
        enabled: yes
        state: started
      tags: ['glusterd']

# filesystem for SD cards
    - name: put xfs on the 3rd, spare, partitiion
      community.general.filesystem:
        dev: '/dev/mmcblk0p3'
        fstype: xfs
        state: present
      tags: ['mkfs']

# create mountpoint
    - name: mkdir /data/glusterfs/myvol1/brick1
      ansible.builtin.file:
        path: /data/glusterfs/myvol1/brick1
        state: directory
      tags: ['mkdir']

# mount SD filesystem 
    - name: mount /dev/mmcblk0p3 on /data/glusterfs/myvol1/brick1
      ansible.posix.mount:
        path: '/data/glusterfs/myvol1/brick1'
        src: '/dev/mmcblk0p3'
        fstype: xfs
        state: present
      tags: ['mount']