---
- hosts: picocluster:!offline
  gather_facts: false
  become: true

  pre_tasks:
  - include_vars: .picocluster.yml
    run_once: true
    tags: ['always']

  tasks:
    - name: modprobe fuse
# apt-get install -y xfsprogs glusterfs-server
    - name: install prerequisites
      apt:
        pkg:
          - xfsprogs 
          - glusterfs-server
# systemctl start glusterd
    - name: start gluster daemon
      ansible.builtin.systemd:
        name: glusterd
        enabled: yes
        state: started

#- hosts: picocluster